# Generated by ariadne-codegen
# Source: rehab_common/graphql/resolvers.graphql

from typing import Any, Dict, List, Optional, Union

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .create_insurance_provider import CreateInsuranceProvider
from .create_many_rehabs import CreateManyRehabs
from .create_rehab import CreateRehab
from .delete_insurance_provider import DeleteInsuranceProvider
from .delete_rehab import DeleteRehab
from .get_insurance_provider_by_id import GetInsuranceProviderById
from .get_insurance_providers import GetInsuranceProviders
from .get_rehab_by_id import GetRehabById
from .get_rehabs import GetRehabs
from .input_types import (
    CreateInsuranceProviderInput,
    CreateProspectiveRehabInput,
    UpdateInsuranceProviderInput,
    UpdateProspectiveRehabInput,
)
from .update_insurance_provider import UpdateInsuranceProvider
from .update_rehab import UpdateRehab


def gql(q: str) -> str:
    return q


class RehabApiClient(AsyncBaseClient):
    async def get_rehabs(
        self,
        search: Union[Optional[str], UnsetType] = UNSET,
        skip: Union[Optional[int], UnsetType] = UNSET,
        take: Union[Optional[int], UnsetType] = UNSET,
        cursor_id: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any
    ) -> GetRehabs:
        query = gql(
            """
            query GetRehabs($search: String, $skip: Int, $take: Int, $cursorId: Int) {
              rehabs(search: $search, skip: $skip, take: $take, cursorId: $cursorId) {
                id
                npi_number
                organization_name
                address
                city
                state
                postal_code
                phone
                taxonomy_code
                taxonomy_desc
                last_updated
                ingested
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "search": search,
            "skip": skip,
            "take": take,
            "cursorId": cursor_id,
        }
        response = await self.execute(
            query=query, operation_name="GetRehabs", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetRehabs.model_validate(data)

    async def get_rehab_by_id(self, id: int, **kwargs: Any) -> GetRehabById:
        query = gql(
            """
            query GetRehabById($id: Int!) {
              rehab(id: $id) {
                id
                npi_number
                organization_name
                address
                city
                state
                postal_code
                phone
                taxonomy_code
                taxonomy_desc
                last_updated
                ingested
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="GetRehabById", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetRehabById.model_validate(data)

    async def create_rehab(
        self, data: CreateProspectiveRehabInput, **kwargs: Any
    ) -> CreateRehab:
        query = gql(
            """
            mutation CreateRehab($data: CreateProspectiveRehabInput!) {
              createRehab(data: $data) {
                id
                npi_number
                organization_name
                address
                city
                state
                postal_code
                phone
                taxonomy_code
                taxonomy_desc
                last_updated
                ingested
              }
            }
            """
        )
        variables: Dict[str, object] = {"data": data}
        response = await self.execute(
            query=query, operation_name="CreateRehab", variables=variables, **kwargs
        )
        _data = self.get_data(response)
        return CreateRehab.model_validate(_data)

    async def create_many_rehabs(
        self, data: List[CreateProspectiveRehabInput], **kwargs: Any
    ) -> CreateManyRehabs:
        query = gql(
            """
            mutation CreateManyRehabs($data: [CreateProspectiveRehabInput!]!) {
              createManyRehabs(data: $data) {
                id
                npi_number
                organization_name
                address
                city
                state
                postal_code
                phone
                taxonomy_code
                taxonomy_desc
                last_updated
                ingested
              }
            }
            """
        )
        variables: Dict[str, object] = {"data": data}
        response = await self.execute(
            query=query,
            operation_name="CreateManyRehabs",
            variables=variables,
            **kwargs
        )
        _data = self.get_data(response)
        return CreateManyRehabs.model_validate(_data)

    async def update_rehab(
        self, id: int, data: UpdateProspectiveRehabInput, **kwargs: Any
    ) -> UpdateRehab:
        query = gql(
            """
            mutation UpdateRehab($id: Int!, $data: UpdateProspectiveRehabInput!) {
              updateRehab(id: $id, data: $data) {
                id
                npi_number
                organization_name
                address
                city
                state
                postal_code
                phone
                taxonomy_code
                taxonomy_desc
                last_updated
                ingested
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id, "data": data}
        response = await self.execute(
            query=query, operation_name="UpdateRehab", variables=variables, **kwargs
        )
        _data = self.get_data(response)
        return UpdateRehab.model_validate(_data)

    async def delete_rehab(self, id: int, **kwargs: Any) -> DeleteRehab:
        query = gql(
            """
            mutation DeleteRehab($id: Int!) {
              deleteRehab(id: $id) {
                id
                npi_number
                organization_name
                address
                city
                state
                postal_code
                phone
                taxonomy_code
                taxonomy_desc
                last_updated
                ingested
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="DeleteRehab", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return DeleteRehab.model_validate(data)

    async def get_insurance_providers(
        self,
        search: Union[Optional[str], UnsetType] = UNSET,
        skip: Union[Optional[int], UnsetType] = UNSET,
        take: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any
    ) -> GetInsuranceProviders:
        query = gql(
            """
            query GetInsuranceProviders($search: String, $skip: Int, $take: Int) {
              insuranceProviders(search: $search, skip: $skip, take: $take) {
                id
                payer_code
                payer_name
                eligibility
                type
              }
            }
            """
        )
        variables: Dict[str, object] = {"search": search, "skip": skip, "take": take}
        response = await self.execute(
            query=query,
            operation_name="GetInsuranceProviders",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetInsuranceProviders.model_validate(data)

    async def get_insurance_provider_by_id(
        self, id: int, **kwargs: Any
    ) -> GetInsuranceProviderById:
        query = gql(
            """
            query GetInsuranceProviderById($id: Int!) {
              insuranceProvider(id: $id) {
                id
                payer_code
                payer_name
                eligibility
                type
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id}
        response = await self.execute(
            query=query,
            operation_name="GetInsuranceProviderById",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetInsuranceProviderById.model_validate(data)

    async def create_insurance_provider(
        self, data: CreateInsuranceProviderInput, **kwargs: Any
    ) -> CreateInsuranceProvider:
        query = gql(
            """
            mutation CreateInsuranceProvider($data: CreateInsuranceProviderInput!) {
              createInsuranceProvider(data: $data) {
                id
                payer_code
                payer_name
                eligibility
                type
              }
            }
            """
        )
        variables: Dict[str, object] = {"data": data}
        response = await self.execute(
            query=query,
            operation_name="CreateInsuranceProvider",
            variables=variables,
            **kwargs
        )
        _data = self.get_data(response)
        return CreateInsuranceProvider.model_validate(_data)

    async def update_insurance_provider(
        self, id: int, data: UpdateInsuranceProviderInput, **kwargs: Any
    ) -> UpdateInsuranceProvider:
        query = gql(
            """
            mutation UpdateInsuranceProvider($id: Int!, $data: UpdateInsuranceProviderInput!) {
              updateInsuranceProvider(id: $id, data: $data) {
                id
                payer_code
                payer_name
                eligibility
                type
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id, "data": data}
        response = await self.execute(
            query=query,
            operation_name="UpdateInsuranceProvider",
            variables=variables,
            **kwargs
        )
        _data = self.get_data(response)
        return UpdateInsuranceProvider.model_validate(_data)

    async def delete_insurance_provider(
        self, id: int, **kwargs: Any
    ) -> DeleteInsuranceProvider:
        query = gql(
            """
            mutation DeleteInsuranceProvider($id: Int!) {
              deleteInsuranceProvider(id: $id) {
                id
                payer_code
                payer_name
                eligibility
                type
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id}
        response = await self.execute(
            query=query,
            operation_name="DeleteInsuranceProvider",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return DeleteInsuranceProvider.model_validate(data)
