# Generated by ariadne-codegen
# Source: rehab_common/graphql/resolvers.graphql

from typing import Any, Dict, List

from .async_base_client import AsyncBaseClient
from .create_many_prospective_rehabs import CreateManyProspectiveRehabs
from .create_prospective_rehab import CreateProspectiveRehab
from .create_rehab_campus_with_connect_or_create import (
    CreateRehabCampusWithConnectOrCreate,
)
from .create_rehab_org_with_connect_or_create import CreateRehabOrgWithConnectOrCreate
from .create_rehab_program_with_connect_or_create import (
    CreateRehabProgramWithConnectOrCreate,
)
from .input_types import (
    CreateProspectiveRehabInput,
    CreateRehabCampusInput,
    CreateRehabOrgInput,
    CreateRehabProgramInput,
    UpdateProspectiveRehabInput,
    UpsertRehabCampusInput,
    UpsertRehabOrgInput,
    UpsertRehabProgramInput,
)
from .update_prospective_rehab import UpdateProspectiveRehab
from .upsert_rehab_campus_with_connect_or_create import (
    UpsertRehabCampusWithConnectOrCreate,
)
from .upsert_rehab_org_with_connect_or_create import UpsertRehabOrgWithConnectOrCreate
from .upsert_rehab_program_with_connect_or_create import (
    UpsertRehabProgramWithConnectOrCreate,
)


def gql(q: str) -> str:
    return q


class RehabApiClient(AsyncBaseClient):
    async def create_prospective_rehab(
        self, data: CreateProspectiveRehabInput, **kwargs: Any
    ) -> CreateProspectiveRehab:
        query = gql(
            """
            mutation CreateProspectiveRehab($data: CreateProspectiveRehabInput!) {
              createProspectiveRehab(data: $data) {
                npi_number
                address
                city
                id
                ingested
                organization_name
                phone
                postal_code
                state
              }
            }
            """
        )
        variables: Dict[str, object] = {"data": data}
        response = await self.execute(
            query=query,
            operation_name="CreateProspectiveRehab",
            variables=variables,
            **kwargs
        )
        _data = self.get_data(response)
        return CreateProspectiveRehab.model_validate(_data)

    async def create_many_prospective_rehabs(
        self, data: List[CreateProspectiveRehabInput], **kwargs: Any
    ) -> CreateManyProspectiveRehabs:
        query = gql(
            """
            mutation CreateManyProspectiveRehabs($data: [CreateProspectiveRehabInput!]!) {
              createManyProspectiveRehabs(data: $data) {
                npi_number
                city
                state
                postal_code
                address
                taxonomy_code
              }
            }
            """
        )
        variables: Dict[str, object] = {"data": data}
        response = await self.execute(
            query=query,
            operation_name="CreateManyProspectiveRehabs",
            variables=variables,
            **kwargs
        )
        _data = self.get_data(response)
        return CreateManyProspectiveRehabs.model_validate(_data)

    async def update_prospective_rehab(
        self,
        data: UpdateProspectiveRehabInput,
        update_prospective_rehab_id: int,
        **kwargs: Any
    ) -> UpdateProspectiveRehab:
        query = gql(
            """
            mutation UpdateProspectiveRehab($data: UpdateProspectiveRehabInput!, $updateProspectiveRehabId: Int!) {
              updateProspectiveRehab(data: $data, id: $updateProspectiveRehabId) {
                id
                ingested
                npi_number
                city
                state
                postal_code
                organization_name
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "data": data,
            "updateProspectiveRehabId": update_prospective_rehab_id,
        }
        response = await self.execute(
            query=query,
            operation_name="UpdateProspectiveRehab",
            variables=variables,
            **kwargs
        )
        _data = self.get_data(response)
        return UpdateProspectiveRehab.model_validate(_data)

    async def create_rehab_org_with_connect_or_create(
        self, data: CreateRehabOrgInput, **kwargs: Any
    ) -> CreateRehabOrgWithConnectOrCreate:
        query = gql(
            """
            mutation CreateRehabOrgWithConnectOrCreate($data: CreateRehabOrgInput!) {
              createRehabOrgWithConnectOrCreate(data: $data) {
                npi_number
                isNonProfit
                createdAt
                description
                id
                legalName
                name
                mainEmail
                mainPhone
                slug
                state
                city
                country
                websiteUrl
                tagline
                fullPrivatePrice
              }
            }
            """
        )
        variables: Dict[str, object] = {"data": data}
        response = await self.execute(
            query=query,
            operation_name="CreateRehabOrgWithConnectOrCreate",
            variables=variables,
            **kwargs
        )
        _data = self.get_data(response)
        return CreateRehabOrgWithConnectOrCreate.model_validate(_data)

    async def upsert_rehab_org_with_connect_or_create(
        self, data: UpsertRehabOrgInput, **kwargs: Any
    ) -> UpsertRehabOrgWithConnectOrCreate:
        query = gql(
            """
            mutation UpsertRehabOrgWithConnectOrCreate($data: UpsertRehabOrgInput!) {
              upsertRehabOrgWithConnectOrCreate(data: $data) {
                city
                country
                description
                fullPrivatePrice
                id
                isNonProfit
                mainEmail
                mainPhone
                name
                npi_number
                websiteUrl
                state
                zip
                slug
                updatedAt
              }
            }
            """
        )
        variables: Dict[str, object] = {"data": data}
        response = await self.execute(
            query=query,
            operation_name="UpsertRehabOrgWithConnectOrCreate",
            variables=variables,
            **kwargs
        )
        _data = self.get_data(response)
        return UpsertRehabOrgWithConnectOrCreate.model_validate(_data)

    async def create_rehab_campus_with_connect_or_create(
        self, data: CreateRehabCampusInput, **kwargs: Any
    ) -> CreateRehabCampusWithConnectOrCreate:
        query = gql(
            """
            mutation CreateRehabCampusWithConnectOrCreate($data: CreateRehabCampusInput!) {
              createRehabCampusWithConnectOrCreate(data: $data) {
                bedsTotal
                city
                country
                id
                name
                latitude
                longitude
                street
                state
                slug
              }
            }
            """
        )
        variables: Dict[str, object] = {"data": data}
        response = await self.execute(
            query=query,
            operation_name="CreateRehabCampusWithConnectOrCreate",
            variables=variables,
            **kwargs
        )
        _data = self.get_data(response)
        return CreateRehabCampusWithConnectOrCreate.model_validate(_data)

    async def upsert_rehab_campus_with_connect_or_create(
        self, data: UpsertRehabCampusInput, **kwargs: Any
    ) -> UpsertRehabCampusWithConnectOrCreate:
        query = gql(
            """
            mutation UpsertRehabCampusWithConnectOrCreate($data: UpsertRehabCampusInput!) {
              upsertRehabCampusWithConnectOrCreate(data: $data) {
                street
                state
                slug
                postalCode
                phone
                name
                longitude
                latitude
                id
                displayName
                description
                city
                country
              }
            }
            """
        )
        variables: Dict[str, object] = {"data": data}
        response = await self.execute(
            query=query,
            operation_name="UpsertRehabCampusWithConnectOrCreate",
            variables=variables,
            **kwargs
        )
        _data = self.get_data(response)
        return UpsertRehabCampusWithConnectOrCreate.model_validate(_data)

    async def create_rehab_program_with_connect_or_create(
        self, data: CreateRehabProgramInput, **kwargs: Any
    ) -> CreateRehabProgramWithConnectOrCreate:
        query = gql(
            """
            mutation CreateRehabProgramWithConnectOrCreate($data: CreateRehabProgramInput!) {
              createRehabProgramWithConnectOrCreate(data: $data) {
                id
                name
                slug
              }
            }
            """
        )
        variables: Dict[str, object] = {"data": data}
        response = await self.execute(
            query=query,
            operation_name="CreateRehabProgramWithConnectOrCreate",
            variables=variables,
            **kwargs
        )
        _data = self.get_data(response)
        return CreateRehabProgramWithConnectOrCreate.model_validate(_data)

    async def upsert_rehab_program_with_connect_or_create(
        self, data: UpsertRehabProgramInput, **kwargs: Any
    ) -> UpsertRehabProgramWithConnectOrCreate:
        query = gql(
            """
            mutation UpsertRehabProgramWithConnectOrCreate($data: UpsertRehabProgramInput!) {
              upsertRehabProgramWithConnectOrCreate(data: $data) {
                name
                id
              }
            }
            """
        )
        variables: Dict[str, object] = {"data": data}
        response = await self.execute(
            query=query,
            operation_name="UpsertRehabProgramWithConnectOrCreate",
            variables=variables,
            **kwargs
        )
        _data = self.get_data(response)
        return UpsertRehabProgramWithConnectOrCreate.model_validate(_data)
