# Generated by ariadne-codegen
# Source: rehab_common/graphql/resolvers.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class CreateManyProspectiveRehabs(BaseModel):
    create_many_prospective_rehabs: List[
        "CreateManyProspectiveRehabsCreateManyProspectiveRehabs"
    ] = Field(alias="createManyProspectiveRehabs")


class CreateManyProspectiveRehabsCreateManyProspectiveRehabs(BaseModel):
    npi_number: str
    city: Optional[str]
    state: Optional[str]
    postal_code: Optional[str]
    address: Optional[str]
    taxonomy_code: Optional[str]


CreateManyProspectiveRehabs.model_rebuild()
