# Generated by ariadne-codegen
# Source: rehab_common/graphql/resolvers.graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class CreateRehabWithConnectOrCreate(BaseModel):
    create_rehab_with_connect_or_create: (
        "CreateRehabWithConnectOrCreateCreateRehabWithConnectOrCreate"
    ) = Field(alias="createRehabWithConnectOrCreate")


class CreateRehabWithConnectOrCreateCreateRehabWithConnectOrCreate(BaseModel):
    city: str
    country: str
    created_at: Any = Field(alias="createdAt")
    description: Optional[str]
    id: str
    npi_number: Optional[str]
    name: str


CreateRehabWithConnectOrCreate.model_rebuild()
