# Generated by ariadne-codegen
# Source: rehab_common/graphql/resolvers.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class CreateManyRehabsWithNested(BaseModel):
    create_many_rehabs_with_nested: List[
        "CreateManyRehabsWithNestedCreateManyRehabsWithNested"
    ] = Field(alias="createManyRehabsWithNested")


class CreateManyRehabsWithNestedCreateManyRehabsWithNested(BaseModel):
    npi_number: Optional[str]
    city: str
    created_at: Any = Field(alias="createdAt")
    country: str


CreateManyRehabsWithNested.model_rebuild()
