# Generated by ariadne-codegen
# Source: rehab_common/graphql/resolvers.graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class CreateRehabOrgWithConnectOrCreate(BaseModel):
    create_rehab_org_with_connect_or_create: (
        "CreateRehabOrgWithConnectOrCreateCreateRehabOrgWithConnectOrCreate"
    ) = Field(alias="createRehabOrgWithConnectOrCreate")


class CreateRehabOrgWithConnectOrCreateCreateRehabOrgWithConnectOrCreate(BaseModel):
    npi_number: Optional[str]
    is_non_profit: Optional[bool] = Field(alias="isNonProfit")
    created_at: Any = Field(alias="createdAt")
    description: Optional[str]
    id: str
    legal_name: Optional[str] = Field(alias="legalName")
    name: str
    main_email: Optional[str] = Field(alias="mainEmail")
    main_phone: Optional[str] = Field(alias="mainPhone")
    slug: str
    state: Optional[str]
    city: Optional[str]
    country: Optional[str]
    website_url: Optional[str] = Field(alias="websiteUrl")
    tagline: Optional[str]
    full_private_price: Optional[int] = Field(alias="fullPrivatePrice")


CreateRehabOrgWithConnectOrCreate.model_rebuild()
