# Generated by ariadne-codegen
# Source: rehab_common/graphql/resolvers.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CreateProspectiveRehab(BaseModel):
    create_prospective_rehab: "CreateProspectiveRehabCreateProspectiveRehab" = Field(
        alias="createProspectiveRehab"
    )


class CreateProspectiveRehabCreateProspectiveRehab(BaseModel):
    npi_number: str
    address: Optional[str]
    city: Optional[str]
    id: int
    ingested: bool
    organization_name: str
    phone: Optional[str]
    postal_code: Optional[str]
    state: Optional[str]


CreateProspectiveRehab.model_rebuild()
