# Generated by ariadne-codegen
# Source: rehab_common/graphql/resolvers.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CreateInsuranceProvider(BaseModel):
    create_insurance_provider: "CreateInsuranceProviderCreateInsuranceProvider" = Field(
        alias="createInsuranceProvider"
    )


class CreateInsuranceProviderCreateInsuranceProvider(BaseModel):
    id: int
    payer_code: str
    payer_name: str
    eligibility: Optional[str]
    type: Optional[str]


CreateInsuranceProvider.model_rebuild()
