# Generated by ariadne-codegen
# Source: rehab_common/graphql/resolvers.graphql

from pydantic import Field

from .base_model import BaseModel


class CreateRehabProgramWithConnectOrCreate(BaseModel):
    create_rehab_program_with_connect_or_create: (
        "CreateRehabProgramWithConnectOrCreateCreateRehabProgramWithConnectOrCreate"
    ) = Field(alias="createRehabProgramWithConnectOrCreate")


class CreateRehabProgramWithConnectOrCreateCreateRehabProgramWithConnectOrCreate(
    BaseModel
):
    id: str
    name: str
    slug: str


CreateRehabProgramWithConnectOrCreate.model_rebuild()
