# Generated by ariadne-codegen
# Source: rehab_common/graphql/resolvers.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CreateRehabCampusWithConnectOrCreate(BaseModel):
    create_rehab_campus_with_connect_or_create: (
        "CreateRehabCampusWithConnectOrCreateCreateRehabCampusWithConnectOrCreate"
    ) = Field(alias="createRehabCampusWithConnectOrCreate")


class CreateRehabCampusWithConnectOrCreateCreateRehabCampusWithConnectOrCreate(
    BaseModel
):
    beds_total: Optional[int] = Field(alias="bedsTotal")
    city: str
    country: str
    id: str
    name: str
    latitude: Optional[float]
    longitude: Optional[float]
    street: str
    state: str
    slug: str


CreateRehabCampusWithConnectOrCreate.model_rebuild()
