# Generated by ariadne-codegen
# Source: rehab_common/graphql/resolvers.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class DeleteInsuranceProvider(BaseModel):
    delete_insurance_provider: "DeleteInsuranceProviderDeleteInsuranceProvider" = Field(
        alias="deleteInsuranceProvider"
    )


class DeleteInsuranceProviderDeleteInsuranceProvider(BaseModel):
    id: int
    payer_code: str
    payer_name: str
    eligibility: Optional[str]
    type: Optional[str]


DeleteInsuranceProvider.model_rebuild()
