# Generated by ariadne-codegen
# Source: rehab_common/graphql/schema.graphql

from enum import Enum


class InsuranceScope(str, Enum):
    CAMPUS = "CAMPUS"
    ORG = "ORG"
    PROGRAM = "PROGRAM"


class LevelOfCareType(str, Enum):
    AFTERCARE = "AFTERCARE"
    DETOX = "DETOX"
    IOP = "IOP"
    OTHER = "OTHER"
    OUTPATIENT = "OUTPATIENT"
    PHP = "PHP"
    RESIDENTIAL = "RESIDENTIAL"
    SOBER_LIVING = "SOBER_LIVING"
    TELEHEALTH = "TELEHEALTH"


class NetworkStatus(str, Enum):
    CASE_BY_CASE = "CASE_BY_CASE"
    IN_NETWORK = "IN_NETWORK"
    OUT_OF_NETWORK = "OUT_OF_NETWORK"
    UNKNOWN = "UNKNOWN"


class ReviewSource(str, Enum):
    FACEBOOK = "FACEBOOK"
    GOOGLE = "GOOGLE"
    HEALTHGRADES = "HEALTHGRADES"
    INTERNAL = "INTERNAL"
    OTHER = "OTHER"


class ReviewerType(str, Enum):
    CLINICIAN = "CLINICIAN"
    LOVED_ONE = "LOVED_ONE"
    OTHER = "OTHER"
    PATIENT = "PATIENT"


class StoryType(str, Enum):
    FAMILY_STORY = "FAMILY_STORY"
    ORIGIN_STORY = "ORIGIN_STORY"
    OTHER = "OTHER"
    OUTCOME_CASE = "OUTCOME_CASE"
    PATIENT_STORY = "PATIENT_STORY"
    PROGRAM_OVERVIEW = "PROGRAM_OVERVIEW"


class WaitlistCategory(str, Enum):
    LONG = "LONG"
    MEDIUM = "MEDIUM"
    NONE = "NONE"
    SHORT = "SHORT"
