# Generated by ariadne-codegen
# Source: rehab_common/graphql/resolvers.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetInsuranceProviders(BaseModel):
    insurance_providers: List["GetInsuranceProvidersInsuranceProviders"] = Field(
        alias="insuranceProviders"
    )


class GetInsuranceProvidersInsuranceProviders(BaseModel):
    id: int
    payer_code: str
    payer_name: str
    eligibility: Optional[str]
    type: Optional[str]


GetInsuranceProviders.model_rebuild()
