# Generated by ariadne-codegen
# Source: rehab_common/graphql/resolvers.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class GetInsuranceProviderById(BaseModel):
    insurance_provider: Optional["GetInsuranceProviderByIdInsuranceProvider"] = Field(
        alias="insuranceProvider"
    )


class GetInsuranceProviderByIdInsuranceProvider(BaseModel):
    id: int
    payer_code: str
    payer_name: str
    eligibility: Optional[str]
    type: Optional[str]


GetInsuranceProviderById.model_rebuild()
