# Generated by ariadne-codegen
# Source: rehab_common/graphql/resolvers.graphql

from typing import Any, Optional

from .base_model import BaseModel


class GetRehabById(BaseModel):
    rehab: Optional["GetRehabByIdRehab"]


class GetRehabByIdRehab(BaseModel):
    id: int
    npi_number: str
    organization_name: str
    address: Optional[str]
    city: Optional[str]
    state: Optional[str]
    postal_code: Optional[str]
    phone: Optional[str]
    taxonomy_code: Optional[str]
    taxonomy_desc: Optional[str]
    last_updated: Optional[Any]
    ingested: bool


GetRehabById.model_rebuild()
