# Generated by ariadne-codegen
# Source: rehab_common/graphql/resolvers.graphql

from typing import Any, List, Optional

from .base_model import BaseModel


class GetRehabs(BaseModel):
    rehabs: List["GetRehabsRehabs"]


class GetRehabsRehabs(BaseModel):
    id: int
    npi_number: str
    organization_name: str
    address: Optional[str]
    city: Optional[str]
    state: Optional[str]
    postal_code: Optional[str]
    phone: Optional[str]
    taxonomy_code: Optional[str]
    taxonomy_desc: Optional[str]
    last_updated: Optional[Any]
    ingested: bool


GetRehabs.model_rebuild()
