# Generated by ariadne-codegen
# Source: rehab_common/graphql/schema.graphql

from typing import Any, Optional

from .base_model import BaseModel


class CreateInsuranceProviderInput(BaseModel):
    eligibility: Optional[str] = None
    payer_code: str
    payer_name: str
    type: Optional[str] = None


class CreateProspectiveRehabInput(BaseModel):
    address: Optional[str] = None
    city: Optional[str] = None
    ingested: bool = False
    last_updated: Optional[Any] = None
    npi_number: str
    organization_name: str
    phone: Optional[str] = None
    postal_code: Optional[str] = None
    state: Optional[str] = None
    taxonomy_code: Optional[str] = None
    taxonomy_desc: Optional[str] = None


class UpdateInsuranceProviderInput(BaseModel):
    eligibility: Optional[str] = None
    payer_name: Optional[str] = None
    type: Optional[str] = None


class UpdateProspectiveRehabInput(BaseModel):
    address: Optional[str] = None
    city: Optional[str] = None
    ingested: Optional[bool] = None
    last_updated: Optional[Any] = None
    organization_name: Optional[str] = None
    phone: Optional[str] = None
    postal_code: Optional[str] = None
    state: Optional[str] = None
    taxonomy_code: Optional[str] = None
    taxonomy_desc: Optional[str] = None
