# Generated by ariadne-codegen
# Source: rehab_common/graphql/schema.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    InsuranceScope,
    LevelOfCareType,
    NetworkStatus,
    ReviewerType,
    ReviewSource,
    StoryType,
    WaitlistCategory,
)


class AccreditationConnectOrCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: Optional[str] = Field(alias="displayName", default=None)
    slug: str


class AccreditationCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: str = Field(alias="displayName")
    slug: str


class AccreditationCreateManyInput(BaseModel):
    items: List["AccreditationCreateInput"]


class AmenityConnectOrCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: Optional[str] = Field(alias="displayName", default=None)
    slug: str


class AmenityCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: str = Field(alias="displayName")
    slug: str


class AmenityCreateManyInput(BaseModel):
    items: List["AmenityCreateInput"]


class BooleanFilter(BaseModel):
    equals: Optional[bool] = None


class CampusReviewCreateInput(BaseModel):
    body: str
    external_url: Optional[str] = Field(alias="externalUrl", default=None)
    is_featured: Optional[bool] = Field(alias="isFeatured", default=None)
    is_verified: Optional[bool] = Field(alias="isVerified", default=None)
    rating: int
    reviewer_name: Optional[str] = Field(alias="reviewerName", default=None)
    reviewer_role: Optional[str] = Field(alias="reviewerRole", default=None)
    reviewer_type: Optional[ReviewerType] = Field(alias="reviewerType", default=None)
    source: Optional[ReviewSource] = None
    title: Optional[str] = None


class CampusStoryCreateInput(BaseModel):
    body: str
    is_featured: Optional[bool] = Field(alias="isFeatured", default=None)
    is_public: Optional[bool] = Field(alias="isPublic", default=None)
    slug: str
    story_type: Optional[StoryType] = Field(alias="storyType", default=None)
    summary: Optional[str] = None
    tags: Optional[List[str]] = None
    title: str


class CampusTestimonialCreateInput(BaseModel):
    attribution_name: Optional[str] = Field(alias="attributionName", default=None)
    attribution_role: Optional[str] = Field(alias="attributionRole", default=None)
    is_featured: Optional[bool] = Field(alias="isFeatured", default=None)
    quote: str
    source: Optional[str] = None


class CreateInsuranceProviderInput(BaseModel):
    eligibility: Optional[str] = None
    payer_code: str
    payer_name: str
    type: Optional[str] = None


class CreateProspectiveRehabInput(BaseModel):
    address: Optional[str] = None
    city: Optional[str] = None
    ingested: bool = False
    last_updated: Optional[Any] = None
    npi_number: str
    organization_name: str
    phone: Optional[str] = None
    postal_code: Optional[str] = None
    state: Optional[str] = None
    taxonomy_code: Optional[str] = None
    taxonomy_desc: Optional[str] = None


class CreateRehabCampusInput(BaseModel):
    accepts_walk_ins: Optional[bool] = Field(alias="acceptsWalkIns", default=None)
    amenities: Optional[List["AmenityConnectOrCreateInput"]] = None
    beds_detox: Optional[int] = Field(alias="bedsDetox", default=None)
    beds_outpatient_capacity: Optional[int] = Field(
        alias="bedsOutpatientCapacity", default=None
    )
    beds_residential: Optional[int] = Field(alias="bedsResidential", default=None)
    beds_total: Optional[int] = Field(alias="bedsTotal", default=None)
    city: str
    country: str
    description: Optional[str] = None
    directions_summary: Optional[str] = Field(alias="directionsSummary", default=None)
    display_name: Optional[str] = Field(alias="displayName", default=None)
    email: Optional[str] = None
    environments: Optional[List["EnvironmentConnectOrCreateInput"]] = None
    gallery_image_urls: Optional[List[str]] = Field(
        alias="galleryImageUrls", default=None
    )
    has_onsite_md: Optional[bool] = Field(alias="hasOnsiteMD", default=None)
    has_twenty_four_hour_nursing: Optional[bool] = Field(
        alias="hasTwentyFourHourNursing", default=None
    )
    hero_image_url: Optional[str] = Field(alias="heroImageUrl", default=None)
    languages: Optional[List["LanguageConnectOrCreateInput"]] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    luxury_tiers: Optional[List["LuxuryTierConnectOrCreateInput"]] = Field(
        alias="luxuryTiers", default=None
    )
    name: str
    phone: Optional[str] = None
    populations: Optional[List["PopulationConnectOrCreateInput"]] = None
    postal_code: str = Field(alias="postalCode")
    primary_environment_slug: Optional[str] = Field(
        alias="primaryEnvironmentSlug", default=None
    )
    primary_luxury_tier_slug: Optional[str] = Field(
        alias="primaryLuxuryTierSlug", default=None
    )
    primary_setting_style_slug: Optional[str] = Field(
        alias="primarySettingStyleSlug", default=None
    )
    rehab_org_id: Optional[str] = Field(alias="rehabOrgId", default=None)
    rehab_org_slug: Optional[str] = Field(alias="rehabOrgSlug", default=None)
    reviews: Optional[List["CampusReviewCreateInput"]] = None
    setting_styles: Optional[List["SettingStyleConnectOrCreateInput"]] = Field(
        alias="settingStyles", default=None
    )
    slug: str
    social_media_profiles: Optional[List["SocialMediaProfileConnectOrCreateInput"]] = (
        Field(alias="socialMediaProfiles", default=None)
    )
    state: str
    stories: Optional[List["CampusStoryCreateInput"]] = None
    street: str
    testimonials: Optional[List["CampusTestimonialCreateInput"]] = None
    time_zone: Optional[str] = Field(alias="timeZone", default=None)
    visiting_hours: Optional[str] = Field(alias="visitingHours", default=None)


class CreateRehabOrgInput(BaseModel):
    accreditations: Optional[List["AccreditationConnectOrCreateInput"]] = None
    amenities: Optional[List["AmenityConnectOrCreateInput"]] = None
    base_currency: Optional[str] = Field(alias="baseCurrency", default=None)
    campuses: Optional[List["RehabCampusConnectOrCreateInput"]] = None
    city: Optional[str] = None
    country: Optional[str] = None
    default_time_zone: Optional[str] = Field(alias="defaultTimeZone", default=None)
    description: Optional[str] = None
    detox_services: Optional[List["DetoxServiceConnectOrCreateInput"]] = Field(
        alias="detoxServices", default=None
    )
    environments: Optional[List["EnvironmentConnectOrCreateInput"]] = None
    full_private_price: Optional[int] = Field(alias="fullPrivatePrice", default=None)
    gallery_image_urls: Optional[List[str]] = Field(
        alias="galleryImageUrls", default=None
    )
    hero_image_url: Optional[str] = Field(alias="heroImageUrl", default=None)
    insurance_payers: Optional[List["RehabInsurancePayerConnectOrCreateInput"]] = Field(
        alias="insurancePayers", default=None
    )
    is_non_profit: Optional[bool] = Field(alias="isNonProfit", default=None)
    languages: Optional[List["LanguageConnectOrCreateInput"]] = None
    legal_name: Optional[str] = Field(alias="legalName", default=None)
    levels_of_care: Optional[List["LevelOfCareConnectOrCreateInput"]] = Field(
        alias="levelsOfCare", default=None
    )
    luxury_tiers: Optional[List["LuxuryTierConnectOrCreateInput"]] = Field(
        alias="luxuryTiers", default=None
    )
    main_email: Optional[str] = Field(alias="mainEmail", default=None)
    main_phone: Optional[str] = Field(alias="mainPhone", default=None)
    name: str
    npi_number: Optional[str] = None
    other_source_urls: Optional[List[str]] = Field(
        alias="otherSourceUrls", default=None
    )
    parent_company: Optional["ParentCompanyConnectOrCreateInput"] = Field(
        alias="parentCompany", default=None
    )
    payment_options: Optional[List["RehabPaymentOptionConnectOrCreateInput"]] = Field(
        alias="paymentOptions", default=None
    )
    populations: Optional[List["PopulationConnectOrCreateInput"]] = None
    primary_source_url: Optional[str] = Field(alias="primarySourceUrl", default=None)
    program_features_global: Optional[
        List["ProgramFeatureGlobalConnectOrCreateInput"]
    ] = Field(alias="programFeaturesGlobal", default=None)
    reviews: Optional[List["OrgReviewCreateInput"]] = None
    services: Optional[List["ServiceConnectOrCreateInput"]] = None
    setting_styles: Optional[List["SettingStyleConnectOrCreateInput"]] = Field(
        alias="settingStyles", default=None
    )
    slug: str
    social_media_profiles: Optional[List["SocialMediaProfileConnectOrCreateInput"]] = (
        Field(alias="socialMediaProfiles", default=None)
    )
    state: Optional[str] = None
    stories: Optional[List["OrgStoryCreateInput"]] = None
    tagline: Optional[str] = None
    testimonials: Optional[List["OrgTestimonialCreateInput"]] = None
    verified_exists: Optional[bool] = Field(alias="verifiedExists", default=None)
    website_url: Optional[str] = Field(alias="websiteUrl", default=None)
    year_founded: Optional[int] = Field(alias="yearFounded", default=None)
    youtube_channels: Optional[List["YoutubeChannelConnectOrCreateInput"]] = Field(
        alias="youtubeChannels", default=None
    )
    zip: Optional[str] = None


class CreateRehabProgramInput(BaseModel):
    accepts_court_ordered: Optional[bool] = Field(
        alias="acceptsCourtOrdered", default=None
    )
    accepts_medically_complex: Optional[bool] = Field(
        alias="acceptsMedicallyComplex", default=None
    )
    accepts_self_referral: Optional[bool] = Field(
        alias="acceptsSelfReferral", default=None
    )
    amenities: Optional[List["AmenityConnectOrCreateInput"]] = None
    campus_id: Optional[str] = Field(alias="campusId", default=None)
    campus_slug: Optional[str] = Field(alias="campusSlug", default=None)
    check_in_days: Optional[List[str]] = Field(alias="checkInDays", default=None)
    clinical_focus_summary: Optional[str] = Field(
        alias="clinicalFocusSummary", default=None
    )
    description: Optional[str] = None
    detox_services: Optional[List["DetoxServiceConnectOrCreateInput"]] = Field(
        alias="detoxServices", default=None
    )
    features: Optional[List["ProgramFeatureGlobalConnectOrCreateInput"]] = None
    gallery_image_urls: Optional[List[str]] = Field(
        alias="galleryImageUrls", default=None
    )
    has_onsite_md: Optional[bool] = Field(alias="hasOnsiteMD", default=None)
    has_twenty_four_hour_nursing: Optional[bool] = Field(
        alias="hasTwentyFourHourNursing", default=None
    )
    hero_image_url: Optional[str] = Field(alias="heroImageUrl", default=None)
    intake_email: Optional[str] = Field(alias="intakeEmail", default=None)
    intake_phone: Optional[str] = Field(alias="intakePhone", default=None)
    is_detox_primary: Optional[bool] = Field(alias="isDetoxPrimary", default=None)
    is_mat_program: Optional[bool] = Field(alias="isMATProgram", default=None)
    languages: Optional[List["LanguageConnectOrCreateInput"]] = None
    level_of_care_slug: str = Field(alias="levelOfCareSlug")
    mat_types: Optional[List["MATTypeConnectOrCreateInput"]] = Field(
        alias="matTypes", default=None
    )
    max_length_of_stay_days: Optional[int] = Field(
        alias="maxLengthOfStayDays", default=None
    )
    min_length_of_stay_days: Optional[int] = Field(
        alias="minLengthOfStayDays", default=None
    )
    name: str
    populations: Optional[List["PopulationConnectOrCreateInput"]] = None
    reviews: Optional[List["ProgramReviewCreateInput"]] = None
    services: Optional[List["ServiceConnectOrCreateInput"]] = None
    session_schedule_summary: Optional[str] = Field(
        alias="sessionScheduleSummary", default=None
    )
    short_name: Optional[str] = Field(alias="shortName", default=None)
    slug: str
    staff_to_patient_ratio: Optional[float] = Field(
        alias="staffToPatientRatio", default=None
    )
    stories: Optional[List["ProgramStoryCreateInput"]] = None
    substances: Optional[List["SubstanceConnectOrCreateInput"]] = None
    target_population_summary: Optional[str] = Field(
        alias="targetPopulationSummary", default=None
    )
    testimonials: Optional[List["ProgramTestimonialCreateInput"]] = None
    typical_length_of_stay_days: Optional[int] = Field(
        alias="typicalLengthOfStayDays", default=None
    )
    waitlist_category: Optional[WaitlistCategory] = Field(
        alias="waitlistCategory", default=None
    )
    waitlist_description: Optional[str] = Field(
        alias="waitlistDescription", default=None
    )


class DetoxServiceConnectOrCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: Optional[str] = Field(alias="displayName", default=None)
    slug: str


class DetoxServiceCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: str = Field(alias="displayName")
    slug: str


class DetoxServiceCreateManyInput(BaseModel):
    items: List["DetoxServiceCreateInput"]


class EnvironmentConnectOrCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: Optional[str] = Field(alias="displayName", default=None)
    slug: str


class EnvironmentCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: str = Field(alias="displayName")
    slug: str


class EnvironmentCreateManyInput(BaseModel):
    items: List["EnvironmentCreateInput"]


class FloatRangeFilter(BaseModel):
    max: Optional[float] = None
    min: Optional[float] = None


class InsurancePayerConnectOrCreateInput(BaseModel):
    company_name: Optional[str] = Field(alias="companyName", default=None)
    description: Optional[str] = None
    display_name: Optional[str] = Field(alias="displayName", default=None)
    id: Optional[str] = None
    payer_type: Optional[str] = Field(alias="payerType", default=None)
    slug: Optional[str] = None


class InsurancePayerCreateInput(BaseModel):
    company_name: str = Field(alias="companyName")
    description: Optional[str] = None
    display_name: str = Field(alias="displayName")
    payer_type: Optional[str] = Field(alias="payerType", default=None)
    slug: str


class InsurancePayerCreateManyInput(BaseModel):
    items: List["InsurancePayerCreateInput"]


class IntRangeFilter(BaseModel):
    max: Optional[int] = None
    min: Optional[int] = None


class LanguageConnectOrCreateInput(BaseModel):
    code: str
    description: Optional[str] = None
    display_name: Optional[str] = Field(alias="displayName", default=None)


class LanguageCreateInput(BaseModel):
    code: str
    description: Optional[str] = None
    display_name: str = Field(alias="displayName")


class LanguageCreateManyInput(BaseModel):
    items: List["LanguageCreateInput"]


class LevelOfCareConnectOrCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: Optional[str] = Field(alias="displayName", default=None)
    slug: str
    type: Optional[LevelOfCareType] = None


class LevelOfCareCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: str = Field(alias="displayName")
    slug: str
    type: Optional[LevelOfCareType] = None


class LevelOfCareCreateManyInput(BaseModel):
    items: List["LevelOfCareCreateInput"]


class LuxuryTierConnectOrCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: Optional[str] = Field(alias="displayName", default=None)
    rank: Optional[int] = None
    slug: str


class LuxuryTierCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: str = Field(alias="displayName")
    rank: Optional[int] = None
    slug: str


class LuxuryTierCreateManyInput(BaseModel):
    items: List["LuxuryTierCreateInput"]


class MATTypeConnectOrCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: Optional[str] = Field(alias="displayName", default=None)
    medication_class: Optional[str] = Field(alias="medicationClass", default=None)
    slug: str


class MATTypeCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: str = Field(alias="displayName")
    medication_class: Optional[str] = Field(alias="medicationClass", default=None)
    slug: str


class MATTypeCreateManyInput(BaseModel):
    items: List["MATTypeCreateInput"]


class OrgReviewCreateInput(BaseModel):
    body: str
    external_url: Optional[str] = Field(alias="externalUrl", default=None)
    is_featured: Optional[bool] = Field(alias="isFeatured", default=None)
    is_verified: Optional[bool] = Field(alias="isVerified", default=None)
    rating: int
    reviewer_name: Optional[str] = Field(alias="reviewerName", default=None)
    reviewer_role: Optional[str] = Field(alias="reviewerRole", default=None)
    reviewer_type: Optional[ReviewerType] = Field(alias="reviewerType", default=None)
    source: Optional[ReviewSource] = None
    title: Optional[str] = None


class OrgStoryCreateInput(BaseModel):
    body: str
    is_featured: Optional[bool] = Field(alias="isFeatured", default=None)
    is_public: Optional[bool] = Field(alias="isPublic", default=None)
    slug: str
    story_type: Optional[StoryType] = Field(alias="storyType", default=None)
    summary: Optional[str] = None
    tags: Optional[List[str]] = None
    title: str


class OrgTestimonialCreateInput(BaseModel):
    attribution_name: Optional[str] = Field(alias="attributionName", default=None)
    attribution_role: Optional[str] = Field(alias="attributionRole", default=None)
    is_featured: Optional[bool] = Field(alias="isFeatured", default=None)
    quote: str
    source: Optional[str] = None


class ParentCompanyConnectOrCreateInput(BaseModel):
    description: Optional[str] = None
    headquarters_city: Optional[str] = Field(alias="headquartersCity", default=None)
    headquarters_country: Optional[str] = Field(
        alias="headquartersCountry", default=None
    )
    headquarters_postal_code: Optional[str] = Field(
        alias="headquartersPostalCode", default=None
    )
    headquarters_state: Optional[str] = Field(alias="headquartersState", default=None)
    headquarters_street: Optional[str] = Field(alias="headquartersStreet", default=None)
    id: Optional[str] = None
    name: Optional[str] = None
    slug: Optional[str] = None
    verified_exists: Optional[bool] = Field(alias="verifiedExists", default=None)
    website_url: Optional[str] = Field(alias="websiteUrl", default=None)


class PaymentOptionConnectOrCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: Optional[str] = Field(alias="displayName", default=None)
    id: Optional[str] = None
    slug: Optional[str] = None


class PaymentOptionCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: str = Field(alias="displayName")
    slug: str


class PaymentOptionCreateManyInput(BaseModel):
    items: List["PaymentOptionCreateInput"]


class PopulationConnectOrCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: Optional[str] = Field(alias="displayName", default=None)
    slug: str


class PopulationCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: str = Field(alias="displayName")
    slug: str


class PopulationCreateManyInput(BaseModel):
    items: List["PopulationCreateInput"]


class ProgramFeatureConnectOrCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: Optional[str] = Field(alias="displayName", default=None)
    id: Optional[str] = None
    slug: Optional[str] = None


class ProgramFeatureCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: str = Field(alias="displayName")
    slug: str


class ProgramFeatureCreateManyInput(BaseModel):
    items: List["ProgramFeatureCreateInput"]


class ProgramFeatureGlobalConnectOrCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: Optional[str] = Field(alias="displayName", default=None)
    slug: str


class ProgramReviewCreateInput(BaseModel):
    body: str
    external_url: Optional[str] = Field(alias="externalUrl", default=None)
    is_featured: Optional[bool] = Field(alias="isFeatured", default=None)
    is_verified: Optional[bool] = Field(alias="isVerified", default=None)
    rating: int
    reviewer_name: Optional[str] = Field(alias="reviewerName", default=None)
    reviewer_role: Optional[str] = Field(alias="reviewerRole", default=None)
    reviewer_type: Optional[ReviewerType] = Field(alias="reviewerType", default=None)
    source: Optional[ReviewSource] = None
    title: Optional[str] = None


class ProgramStoryCreateInput(BaseModel):
    body: str
    is_featured: Optional[bool] = Field(alias="isFeatured", default=None)
    is_public: Optional[bool] = Field(alias="isPublic", default=None)
    slug: str
    story_type: Optional[StoryType] = Field(alias="storyType", default=None)
    summary: Optional[str] = None
    tags: Optional[List[str]] = None
    title: str


class ProgramTestimonialCreateInput(BaseModel):
    attribution_name: Optional[str] = Field(alias="attributionName", default=None)
    attribution_role: Optional[str] = Field(alias="attributionRole", default=None)
    is_featured: Optional[bool] = Field(alias="isFeatured", default=None)
    quote: str
    source: Optional[str] = None


class RehabCampusConnectOrCreateInput(BaseModel):
    create: Optional["RehabCampusCreateForOrgInput"] = None
    id: Optional[str] = None
    slug: Optional[str] = None


class RehabCampusCreateForOrgInput(BaseModel):
    accepts_walk_ins: Optional[bool] = Field(alias="acceptsWalkIns", default=None)
    beds_detox: Optional[int] = Field(alias="bedsDetox", default=None)
    beds_outpatient_capacity: Optional[int] = Field(
        alias="bedsOutpatientCapacity", default=None
    )
    beds_residential: Optional[int] = Field(alias="bedsResidential", default=None)
    beds_total: Optional[int] = Field(alias="bedsTotal", default=None)
    city: str
    country: str
    description: Optional[str] = None
    directions_summary: Optional[str] = Field(alias="directionsSummary", default=None)
    display_name: Optional[str] = Field(alias="displayName", default=None)
    email: Optional[str] = None
    gallery_image_urls: Optional[List[str]] = Field(
        alias="galleryImageUrls", default=None
    )
    has_onsite_md: Optional[bool] = Field(alias="hasOnsiteMD", default=None)
    has_twenty_four_hour_nursing: Optional[bool] = Field(
        alias="hasTwentyFourHourNursing", default=None
    )
    hero_image_url: Optional[str] = Field(alias="heroImageUrl", default=None)
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    name: str
    phone: Optional[str] = None
    postal_code: str = Field(alias="postalCode")
    primary_environment_slug: Optional[str] = Field(
        alias="primaryEnvironmentSlug", default=None
    )
    primary_luxury_tier_slug: Optional[str] = Field(
        alias="primaryLuxuryTierSlug", default=None
    )
    primary_setting_style_slug: Optional[str] = Field(
        alias="primarySettingStyleSlug", default=None
    )
    slug: str
    state: str
    street: str
    time_zone: Optional[str] = Field(alias="timeZone", default=None)
    visiting_hours: Optional[str] = Field(alias="visitingHours", default=None)


class RehabCampusFilterInput(BaseModel):
    accepts_walk_ins: Optional["BooleanFilter"] = Field(
        alias="acceptsWalkIns", default=None
    )
    beds_detox: Optional["IntRangeFilter"] = Field(alias="bedsDetox", default=None)
    beds_outpatient_capacity: Optional["IntRangeFilter"] = Field(
        alias="bedsOutpatientCapacity", default=None
    )
    beds_residential: Optional["IntRangeFilter"] = Field(
        alias="bedsResidential", default=None
    )
    beds_total: Optional["IntRangeFilter"] = Field(alias="bedsTotal", default=None)
    campus_amenity_ids: Optional[List[str]] = Field(
        alias="campusAmenityIds", default=None
    )
    campus_environment_ids: Optional[List[str]] = Field(
        alias="campusEnvironmentIds", default=None
    )
    campus_language_ids: Optional[List[str]] = Field(
        alias="campusLanguageIds", default=None
    )
    campus_luxury_tier_ids: Optional[List[str]] = Field(
        alias="campusLuxuryTierIds", default=None
    )
    campus_population_ids: Optional[List[str]] = Field(
        alias="campusPopulationIds", default=None
    )
    campus_setting_style_ids: Optional[List[str]] = Field(
        alias="campusSettingStyleIds", default=None
    )
    cities: Optional[List[str]] = None
    countries: Optional[List[str]] = None
    has_onsite_md: Optional["BooleanFilter"] = Field(alias="hasOnsiteMD", default=None)
    has_twenty_four_hour_nursing: Optional["BooleanFilter"] = Field(
        alias="hasTwentyFourHourNursing", default=None
    )
    ids: Optional[List[str]] = None
    insurance_payer_ids: Optional[List[str]] = Field(
        alias="insurancePayerIds", default=None
    )
    near_lat: Optional[float] = Field(alias="nearLat", default=None)
    near_lng: Optional[float] = Field(alias="nearLng", default=None)
    payment_option_ids: Optional[List[str]] = Field(
        alias="paymentOptionIds", default=None
    )
    postal_codes: Optional[List[str]] = Field(alias="postalCodes", default=None)
    primary_environment_ids: Optional[List[str]] = Field(
        alias="primaryEnvironmentIds", default=None
    )
    primary_luxury_tier_ids: Optional[List[str]] = Field(
        alias="primaryLuxuryTierIds", default=None
    )
    primary_setting_style_ids: Optional[List[str]] = Field(
        alias="primarySettingStyleIds", default=None
    )
    program_amenity_ids: Optional[List[str]] = Field(
        alias="programAmenityIds", default=None
    )
    program_detox_service_ids: Optional[List[str]] = Field(
        alias="programDetoxServiceIds", default=None
    )
    program_feature_ids: Optional[List[str]] = Field(
        alias="programFeatureIds", default=None
    )
    program_language_ids: Optional[List[str]] = Field(
        alias="programLanguageIds", default=None
    )
    program_level_of_care_ids: Optional[List[str]] = Field(
        alias="programLevelOfCareIds", default=None
    )
    program_mat_type_ids: Optional[List[str]] = Field(
        alias="programMATTypeIds", default=None
    )
    program_population_ids: Optional[List[str]] = Field(
        alias="programPopulationIds", default=None
    )
    program_service_ids: Optional[List[str]] = Field(
        alias="programServiceIds", default=None
    )
    program_substance_ids: Optional[List[str]] = Field(
        alias="programSubstanceIds", default=None
    )
    radius_km: Optional[float] = Field(alias="radiusKm", default=None)
    rehab_org_ids: Optional[List[str]] = Field(alias="rehabOrgIds", default=None)
    search: Optional[str] = None
    skip: Optional[float] = None
    slugs: Optional[List[str]] = None
    states: Optional[List[str]] = None
    take: Optional[float] = None


class RehabInsurancePayerConnectOrCreateInput(BaseModel):
    accepts_out_of_network_with_oop_cap: Optional[bool] = Field(
        alias="acceptsOutOfNetworkWithOopCap", default=None
    )
    average_admission_price: Optional[int] = Field(
        alias="averageAdmissionPrice", default=None
    )
    estimated_patient_oop_max: Optional[int] = Field(
        alias="estimatedPatientOopMax", default=None
    )
    estimated_patient_oop_min: Optional[int] = Field(
        alias="estimatedPatientOopMin", default=None
    )
    insurance_payer: "InsurancePayerConnectOrCreateInput" = Field(
        alias="insurancePayer"
    )
    network_status: Optional[NetworkStatus] = Field(alias="networkStatus", default=None)
    notes: Optional[str] = None
    overview: Optional[str] = None
    requires_preauth: Optional[bool] = Field(alias="requiresPreauth", default=None)
    scope: Optional[InsuranceScope] = None


class RehabOrgFilterInput(BaseModel):
    accreditation_ids: Optional[List[str]] = Field(
        alias="accreditationIds", default=None
    )
    amenity_ids: Optional[List[str]] = Field(alias="amenityIds", default=None)
    campus_states: Optional[List[str]] = Field(alias="campusStates", default=None)
    cities: Optional[List[str]] = None
    countries: Optional[List[str]] = None
    detox_service_ids: Optional[List[str]] = Field(
        alias="detoxServiceIds", default=None
    )
    environment_ids: Optional[List[str]] = Field(alias="environmentIds", default=None)
    full_private_price: Optional["IntRangeFilter"] = Field(
        alias="fullPrivatePrice", default=None
    )
    ids: Optional[List[str]] = None
    insurance_payer_ids: Optional[List[str]] = Field(
        alias="insurancePayerIds", default=None
    )
    is_non_profit: Optional["BooleanFilter"] = Field(alias="isNonProfit", default=None)
    language_ids: Optional[List[str]] = Field(alias="languageIds", default=None)
    legal_name: Optional["StringFilter"] = Field(alias="legalName", default=None)
    level_of_care_ids: Optional[List[str]] = Field(alias="levelOfCareIds", default=None)
    luxury_tier_ids: Optional[List[str]] = Field(alias="luxuryTierIds", default=None)
    name: Optional["StringFilter"] = None
    npi_number: Optional["StringFilter"] = Field(alias="npiNumber", default=None)
    payment_option_ids: Optional[List[str]] = Field(
        alias="paymentOptionIds", default=None
    )
    population_ids: Optional[List[str]] = Field(alias="populationIds", default=None)
    program_feature_global_ids: Optional[List[str]] = Field(
        alias="programFeatureGlobalIds", default=None
    )
    program_level_of_care_ids: Optional[List[str]] = Field(
        alias="programLevelOfCareIds", default=None
    )
    program_mat_type_ids: Optional[List[str]] = Field(
        alias="programMATTypeIds", default=None
    )
    program_substance_ids: Optional[List[str]] = Field(
        alias="programSubstanceIds", default=None
    )
    search: Optional[str] = None
    service_ids: Optional[List[str]] = Field(alias="serviceIds", default=None)
    setting_style_ids: Optional[List[str]] = Field(
        alias="settingStyleIds", default=None
    )
    skip: Optional[float] = None
    slugs: Optional[List[str]] = None
    states: Optional[List[str]] = None
    take: Optional[float] = None
    verified_exists: Optional["BooleanFilter"] = Field(
        alias="verifiedExists", default=None
    )
    year_founded: Optional["IntRangeFilter"] = Field(alias="yearFounded", default=None)
    zips: Optional[List[str]] = None


class RehabPaymentOptionConnectOrCreateInput(BaseModel):
    description_override: Optional[str] = Field(
        alias="descriptionOverride", default=None
    )
    payment_option: "PaymentOptionConnectOrCreateInput" = Field(alias="paymentOption")


class RehabProgramFilterInput(BaseModel):
    accepts_court_ordered: Optional["BooleanFilter"] = Field(
        alias="acceptsCourtOrdered", default=None
    )
    accepts_medically_complex: Optional["BooleanFilter"] = Field(
        alias="acceptsMedicallyComplex", default=None
    )
    accepts_self_referral: Optional["BooleanFilter"] = Field(
        alias="acceptsSelfReferral", default=None
    )
    amenity_ids: Optional[List[str]] = Field(alias="amenityIds", default=None)
    campus_ids: Optional[List[str]] = Field(alias="campusIds", default=None)
    detox_service_ids: Optional[List[str]] = Field(
        alias="detoxServiceIds", default=None
    )
    feature_ids: Optional[List[str]] = Field(alias="featureIds", default=None)
    has_onsite_md: Optional["BooleanFilter"] = Field(alias="hasOnsiteMD", default=None)
    has_twenty_four_hour_nursing: Optional["BooleanFilter"] = Field(
        alias="hasTwentyFourHourNursing", default=None
    )
    ids: Optional[List[str]] = None
    insurance_payer_ids: Optional[List[str]] = Field(
        alias="insurancePayerIds", default=None
    )
    is_detox_primary: Optional["BooleanFilter"] = Field(
        alias="isDetoxPrimary", default=None
    )
    is_mat_program: Optional["BooleanFilter"] = Field(
        alias="isMATProgram", default=None
    )
    language_ids: Optional[List[str]] = Field(alias="languageIds", default=None)
    level_of_care_ids: Optional[List[str]] = Field(alias="levelOfCareIds", default=None)
    mat_type_ids: Optional[List[str]] = Field(alias="matTypeIds", default=None)
    max_length_of_stay_days: Optional["IntRangeFilter"] = Field(
        alias="maxLengthOfStayDays", default=None
    )
    min_length_of_stay_days: Optional["IntRangeFilter"] = Field(
        alias="minLengthOfStayDays", default=None
    )
    name: Optional["StringFilter"] = None
    payment_option_ids: Optional[List[str]] = Field(
        alias="paymentOptionIds", default=None
    )
    population_ids: Optional[List[str]] = Field(alias="populationIds", default=None)
    rehab_org_ids: Optional[List[str]] = Field(alias="rehabOrgIds", default=None)
    search: Optional[str] = None
    service_ids: Optional[List[str]] = Field(alias="serviceIds", default=None)
    session_schedule_contains: Optional[str] = Field(
        alias="sessionScheduleContains", default=None
    )
    skip: Optional[float] = None
    slugs: Optional[List[str]] = None
    staff_to_patient_ratio: Optional["FloatRangeFilter"] = Field(
        alias="staffToPatientRatio", default=None
    )
    substance_ids: Optional[List[str]] = Field(alias="substanceIds", default=None)
    take: Optional[float] = None
    typical_length_of_stay_days: Optional["IntRangeFilter"] = Field(
        alias="typicalLengthOfStayDays", default=None
    )
    waitlist_categories: Optional[List[WaitlistCategory]] = Field(
        alias="waitlistCategories", default=None
    )


class ServiceConnectOrCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: Optional[str] = Field(alias="displayName", default=None)
    slug: str


class ServiceCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: str = Field(alias="displayName")
    slug: str


class ServiceCreateManyInput(BaseModel):
    items: List["ServiceCreateInput"]


class SettingStyleConnectOrCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: Optional[str] = Field(alias="displayName", default=None)
    slug: str


class SettingStyleCreateInput(BaseModel):
    description: Optional[str] = None
    display_name: str = Field(alias="displayName")
    slug: str


class SettingStyleCreateManyInput(BaseModel):
    items: List["SettingStyleCreateInput"]


class SocialMediaProfileConnectOrCreateInput(BaseModel):
    id: Optional[str] = None
    platform: str
    url: str


class StringFilter(BaseModel):
    contains: Optional[str] = None
    ends_with: Optional[str] = Field(alias="endsWith", default=None)
    equals: Optional[str] = None
    in_: Optional[List[str]] = Field(alias="in", default=None)
    insensitive: Optional[bool] = None
    starts_with: Optional[str] = Field(alias="startsWith", default=None)


class SubstanceConnectOrCreateInput(BaseModel):
    category: Optional[str] = None
    description: Optional[str] = None
    display_name: Optional[str] = Field(alias="displayName", default=None)
    slug: str


class SubstanceCreateInput(BaseModel):
    category: Optional[str] = None
    description: Optional[str] = None
    display_name: str = Field(alias="displayName")
    slug: str


class SubstanceCreateManyInput(BaseModel):
    items: List["SubstanceCreateInput"]


class UpdateInsuranceProviderInput(BaseModel):
    eligibility: Optional[str] = None
    payer_name: Optional[str] = None
    type: Optional[str] = None


class UpdateProspectiveRehabInput(BaseModel):
    address: Optional[str] = None
    city: Optional[str] = None
    ingested: Optional[bool] = None
    last_updated: Optional[Any] = None
    organization_name: Optional[str] = None
    phone: Optional[str] = None
    postal_code: Optional[str] = None
    state: Optional[str] = None
    taxonomy_code: Optional[str] = None
    taxonomy_desc: Optional[str] = None


class UpsertRehabCampusInput(BaseModel):
    accepts_walk_ins: Optional[bool] = Field(alias="acceptsWalkIns", default=None)
    amenities: Optional[List["AmenityConnectOrCreateInput"]] = None
    beds_detox: Optional[int] = Field(alias="bedsDetox", default=None)
    beds_outpatient_capacity: Optional[int] = Field(
        alias="bedsOutpatientCapacity", default=None
    )
    beds_residential: Optional[int] = Field(alias="bedsResidential", default=None)
    beds_total: Optional[int] = Field(alias="bedsTotal", default=None)
    city: Optional[str] = None
    country: Optional[str] = None
    description: Optional[str] = None
    directions_summary: Optional[str] = Field(alias="directionsSummary", default=None)
    display_name: Optional[str] = Field(alias="displayName", default=None)
    email: Optional[str] = None
    environments: Optional[List["EnvironmentConnectOrCreateInput"]] = None
    has_onsite_md: Optional[bool] = Field(alias="hasOnsiteMD", default=None)
    has_twenty_four_hour_nursing: Optional[bool] = Field(
        alias="hasTwentyFourHourNursing", default=None
    )
    id: str
    languages: Optional[List["LanguageConnectOrCreateInput"]] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    luxury_tiers: Optional[List["LuxuryTierConnectOrCreateInput"]] = Field(
        alias="luxuryTiers", default=None
    )
    name: Optional[str] = None
    phone: Optional[str] = None
    populations: Optional[List["PopulationConnectOrCreateInput"]] = None
    postal_code: Optional[str] = Field(alias="postalCode", default=None)
    primary_environment_slug: Optional[str] = Field(
        alias="primaryEnvironmentSlug", default=None
    )
    primary_luxury_tier_slug: Optional[str] = Field(
        alias="primaryLuxuryTierSlug", default=None
    )
    primary_setting_style_slug: Optional[str] = Field(
        alias="primarySettingStyleSlug", default=None
    )
    rehab_org_id: Optional[str] = Field(alias="rehabOrgId", default=None)
    rehab_org_slug: Optional[str] = Field(alias="rehabOrgSlug", default=None)
    reviews: Optional[List["CampusReviewCreateInput"]] = None
    setting_styles: Optional[List["SettingStyleConnectOrCreateInput"]] = Field(
        alias="settingStyles", default=None
    )
    slug: Optional[str] = None
    social_media_profiles: Optional[List["SocialMediaProfileConnectOrCreateInput"]] = (
        Field(alias="socialMediaProfiles", default=None)
    )
    state: Optional[str] = None
    stories: Optional[List["CampusStoryCreateInput"]] = None
    street: Optional[str] = None
    testimonials: Optional[List["CampusTestimonialCreateInput"]] = None
    time_zone: Optional[str] = Field(alias="timeZone", default=None)
    visiting_hours: Optional[str] = Field(alias="visitingHours", default=None)


class UpsertRehabOrgInput(BaseModel):
    accreditations: Optional[List["AccreditationConnectOrCreateInput"]] = None
    amenities: Optional[List["AmenityConnectOrCreateInput"]] = None
    base_currency: Optional[str] = Field(alias="baseCurrency", default=None)
    campuses: Optional[List["RehabCampusConnectOrCreateInput"]] = None
    city: Optional[str] = None
    country: Optional[str] = None
    default_time_zone: Optional[str] = Field(alias="defaultTimeZone", default=None)
    description: Optional[str] = None
    detox_services: Optional[List["DetoxServiceConnectOrCreateInput"]] = Field(
        alias="detoxServices", default=None
    )
    environments: Optional[List["EnvironmentConnectOrCreateInput"]] = None
    full_private_price: Optional[int] = Field(alias="fullPrivatePrice", default=None)
    gallery_image_urls: Optional[List[str]] = Field(
        alias="galleryImageUrls", default=None
    )
    hero_image_url: Optional[str] = Field(alias="heroImageUrl", default=None)
    id: str
    insurance_payers: Optional[List["RehabInsurancePayerConnectOrCreateInput"]] = Field(
        alias="insurancePayers", default=None
    )
    is_non_profit: Optional[bool] = Field(alias="isNonProfit", default=None)
    languages: Optional[List["LanguageConnectOrCreateInput"]] = None
    legal_name: Optional[str] = Field(alias="legalName", default=None)
    levels_of_care: Optional[List["LevelOfCareConnectOrCreateInput"]] = Field(
        alias="levelsOfCare", default=None
    )
    luxury_tiers: Optional[List["LuxuryTierConnectOrCreateInput"]] = Field(
        alias="luxuryTiers", default=None
    )
    main_email: Optional[str] = Field(alias="mainEmail", default=None)
    main_phone: Optional[str] = Field(alias="mainPhone", default=None)
    name: Optional[str] = None
    npi_number: Optional[str] = None
    other_source_urls: Optional[List[str]] = Field(
        alias="otherSourceUrls", default=None
    )
    parent_company: Optional["ParentCompanyConnectOrCreateInput"] = Field(
        alias="parentCompany", default=None
    )
    payment_options: Optional[List["RehabPaymentOptionConnectOrCreateInput"]] = Field(
        alias="paymentOptions", default=None
    )
    populations: Optional[List["PopulationConnectOrCreateInput"]] = None
    primary_source_url: Optional[str] = Field(alias="primarySourceUrl", default=None)
    program_features_global: Optional[
        List["ProgramFeatureGlobalConnectOrCreateInput"]
    ] = Field(alias="programFeaturesGlobal", default=None)
    reviews: Optional[List["OrgReviewCreateInput"]] = None
    services: Optional[List["ServiceConnectOrCreateInput"]] = None
    setting_styles: Optional[List["SettingStyleConnectOrCreateInput"]] = Field(
        alias="settingStyles", default=None
    )
    slug: Optional[str] = None
    social_media_profiles: Optional[List["SocialMediaProfileConnectOrCreateInput"]] = (
        Field(alias="socialMediaProfiles", default=None)
    )
    state: Optional[str] = None
    stories: Optional[List["OrgStoryCreateInput"]] = None
    tagline: Optional[str] = None
    testimonials: Optional[List["OrgTestimonialCreateInput"]] = None
    verified_exists: Optional[bool] = Field(alias="verifiedExists", default=None)
    website_url: Optional[str] = Field(alias="websiteUrl", default=None)
    year_founded: Optional[int] = Field(alias="yearFounded", default=None)
    youtube_channels: Optional[List["YoutubeChannelConnectOrCreateInput"]] = Field(
        alias="youtubeChannels", default=None
    )
    zip: Optional[str] = None


class UpsertRehabProgramInput(BaseModel):
    accepts_court_ordered: Optional[bool] = Field(
        alias="acceptsCourtOrdered", default=None
    )
    accepts_medically_complex: Optional[bool] = Field(
        alias="acceptsMedicallyComplex", default=None
    )
    accepts_self_referral: Optional[bool] = Field(
        alias="acceptsSelfReferral", default=None
    )
    amenities: Optional[List["AmenityConnectOrCreateInput"]] = None
    campus_id: Optional[str] = Field(alias="campusId", default=None)
    campus_slug: Optional[str] = Field(alias="campusSlug", default=None)
    check_in_days: Optional[List[str]] = Field(alias="checkInDays", default=None)
    clinical_focus_summary: Optional[str] = Field(
        alias="clinicalFocusSummary", default=None
    )
    description: Optional[str] = None
    detox_services: Optional[List["DetoxServiceConnectOrCreateInput"]] = Field(
        alias="detoxServices", default=None
    )
    features: Optional[List["ProgramFeatureConnectOrCreateInput"]] = None
    has_onsite_md: Optional[bool] = Field(alias="hasOnsiteMD", default=None)
    has_twenty_four_hour_nursing: Optional[bool] = Field(
        alias="hasTwentyFourHourNursing", default=None
    )
    id: str
    intake_email: Optional[str] = Field(alias="intakeEmail", default=None)
    intake_phone: Optional[str] = Field(alias="intakePhone", default=None)
    is_detox_primary: Optional[bool] = Field(alias="isDetoxPrimary", default=None)
    is_mat_program: Optional[bool] = Field(alias="isMATProgram", default=None)
    languages: Optional[List["LanguageConnectOrCreateInput"]] = None
    level_of_care_slug: Optional[str] = Field(alias="levelOfCareSlug", default=None)
    mat_types: Optional[List["MATTypeConnectOrCreateInput"]] = Field(
        alias="matTypes", default=None
    )
    max_length_of_stay_days: Optional[int] = Field(
        alias="maxLengthOfStayDays", default=None
    )
    min_length_of_stay_days: Optional[int] = Field(
        alias="minLengthOfStayDays", default=None
    )
    name: Optional[str] = None
    populations: Optional[List["PopulationConnectOrCreateInput"]] = None
    reviews: Optional[List["ProgramReviewCreateInput"]] = None
    services: Optional[List["ServiceConnectOrCreateInput"]] = None
    session_schedule_summary: Optional[str] = Field(
        alias="sessionScheduleSummary", default=None
    )
    short_name: Optional[str] = Field(alias="shortName", default=None)
    slug: Optional[str] = None
    staff_to_patient_ratio: Optional[float] = Field(
        alias="staffToPatientRatio", default=None
    )
    stories: Optional[List["ProgramStoryCreateInput"]] = None
    substances: Optional[List["SubstanceConnectOrCreateInput"]] = None
    target_population_summary: Optional[str] = Field(
        alias="targetPopulationSummary", default=None
    )
    testimonials: Optional[List["ProgramTestimonialCreateInput"]] = None
    typical_length_of_stay_days: Optional[int] = Field(
        alias="typicalLengthOfStayDays", default=None
    )
    waitlist_category: Optional[WaitlistCategory] = Field(
        alias="waitlistCategory", default=None
    )
    waitlist_description: Optional[str] = Field(
        alias="waitlistDescription", default=None
    )


class YoutubeChannelConnectOrCreateInput(BaseModel):
    id: Optional[str] = None
    url: str


AccreditationCreateManyInput.model_rebuild()
AmenityCreateManyInput.model_rebuild()
CreateRehabCampusInput.model_rebuild()
CreateRehabOrgInput.model_rebuild()
CreateRehabProgramInput.model_rebuild()
DetoxServiceCreateManyInput.model_rebuild()
EnvironmentCreateManyInput.model_rebuild()
InsurancePayerCreateManyInput.model_rebuild()
LanguageCreateManyInput.model_rebuild()
LevelOfCareCreateManyInput.model_rebuild()
LuxuryTierCreateManyInput.model_rebuild()
MATTypeCreateManyInput.model_rebuild()
PaymentOptionCreateManyInput.model_rebuild()
PopulationCreateManyInput.model_rebuild()
ProgramFeatureCreateManyInput.model_rebuild()
RehabCampusConnectOrCreateInput.model_rebuild()
RehabCampusFilterInput.model_rebuild()
RehabInsurancePayerConnectOrCreateInput.model_rebuild()
RehabOrgFilterInput.model_rebuild()
RehabPaymentOptionConnectOrCreateInput.model_rebuild()
RehabProgramFilterInput.model_rebuild()
ServiceCreateManyInput.model_rebuild()
SettingStyleCreateManyInput.model_rebuild()
SubstanceCreateManyInput.model_rebuild()
UpsertRehabCampusInput.model_rebuild()
UpsertRehabOrgInput.model_rebuild()
UpsertRehabProgramInput.model_rebuild()
