# Generated by ariadne-codegen
# Source: rehab_common/graphql/resolvers.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateProspectiveRehab(BaseModel):
    update_prospective_rehab: "UpdateProspectiveRehabUpdateProspectiveRehab" = Field(
        alias="updateProspectiveRehab"
    )


class UpdateProspectiveRehabUpdateProspectiveRehab(BaseModel):
    id: int
    ingested: bool
    npi_number: str
    city: Optional[str]
    state: Optional[str]
    postal_code: Optional[str]
    organization_name: str


UpdateProspectiveRehab.model_rebuild()
