# Generated by ariadne-codegen
# Source: rehab_common/graphql/resolvers.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateInsuranceProvider(BaseModel):
    update_insurance_provider: "UpdateInsuranceProviderUpdateInsuranceProvider" = Field(
        alias="updateInsuranceProvider"
    )


class UpdateInsuranceProviderUpdateInsuranceProvider(BaseModel):
    id: int
    payer_code: str
    payer_name: str
    eligibility: Optional[str]
    type: Optional[str]


UpdateInsuranceProvider.model_rebuild()
