# Generated by ariadne-codegen
# Source: rehab_common/graphql/resolvers.graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class UpsertRehabOrgWithConnectOrCreate(BaseModel):
    upsert_rehab_org_with_connect_or_create: (
        "UpsertRehabOrgWithConnectOrCreateUpsertRehabOrgWithConnectOrCreate"
    ) = Field(alias="upsertRehabOrgWithConnectOrCreate")


class UpsertRehabOrgWithConnectOrCreateUpsertRehabOrgWithConnectOrCreate(BaseModel):
    city: Optional[str]
    country: Optional[str]
    description: Optional[str]
    full_private_price: Optional[int] = Field(alias="fullPrivatePrice")
    id: str
    is_non_profit: Optional[bool] = Field(alias="isNonProfit")
    main_email: Optional[str] = Field(alias="mainEmail")
    main_phone: Optional[str] = Field(alias="mainPhone")
    name: str
    npi_number: Optional[str]
    website_url: Optional[str] = Field(alias="websiteUrl")
    state: Optional[str]
    zip: Optional[str]
    slug: str
    updated_at: Any = Field(alias="updatedAt")


UpsertRehabOrgWithConnectOrCreate.model_rebuild()
