# Generated by ariadne-codegen
# Source: rehab_common/graphql/resolvers.graphql

from pydantic import Field

from .base_model import BaseModel


class UpsertRehabProgramWithConnectOrCreate(BaseModel):
    upsert_rehab_program_with_connect_or_create: (
        "UpsertRehabProgramWithConnectOrCreateUpsertRehabProgramWithConnectOrCreate"
    ) = Field(alias="upsertRehabProgramWithConnectOrCreate")


class UpsertRehabProgramWithConnectOrCreateUpsertRehabProgramWithConnectOrCreate(
    BaseModel
):
    name: str
    id: str


UpsertRehabProgramWithConnectOrCreate.model_rebuild()
