# Generated by ariadne-codegen
# Source: rehab_common/graphql/resolvers.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpsertRehabCampusWithConnectOrCreate(BaseModel):
    upsert_rehab_campus_with_connect_or_create: (
        "UpsertRehabCampusWithConnectOrCreateUpsertRehabCampusWithConnectOrCreate"
    ) = Field(alias="upsertRehabCampusWithConnectOrCreate")


class UpsertRehabCampusWithConnectOrCreateUpsertRehabCampusWithConnectOrCreate(
    BaseModel
):
    street: str
    state: str
    slug: str
    postal_code: str = Field(alias="postalCode")
    phone: Optional[str]
    name: str
    longitude: Optional[float]
    latitude: Optional[float]
    id: str
    display_name: Optional[str] = Field(alias="displayName")
    description: Optional[str]
    city: str
    country: str


UpsertRehabCampusWithConnectOrCreate.model_rebuild()
